/**
 * Privacy policy content (EN/HE).
 *
 * Kept out of `translations.ts` on purpose: that file is a flat dictionary for
 * UI chrome, and the policy is long-form structured prose. Structural parity
 * between the two languages is enforced by `src/test/privacyPolicy.test.ts`.
 *
 * The text describes what the app actually does. If data handling changes
 * (new processor, analytics, a new table holding personal data), update this
 * file AND bump `lastUpdated`.
 */

import type { Language } from "./translations";

export interface PolicySection {
  /** Section heading. */
  heading: string;
  /** Paragraphs rendered above the bullet list. */
  body: string[];
  /** Optional bullet list rendered after the paragraphs. */
  bullets?: string[];
}

export interface PolicyContent {
  title: string;
  /** Human-readable "last updated" date, already localized. */
  lastUpdated: string;
  /** Lead paragraphs shown before the first section. */
  intro: string[];
  sections: PolicySection[];
}

/** Contact address for privacy requests. Also used by the page's mailto link. */
export const PRIVACY_CONTACT_EMAIL = "privacy@runimarket.org";

/**
 * Wraps an LTR token (email, domain) in a bidi isolate so it keeps its own
 * direction inside Hebrew RTL prose. Without this, "@post.runi.ac.il" renders
 * as "post.runi.ac.il@" because the leading "@" is a neutral character and
 * gets reordered into the surrounding RTL run.
 */
const ltr = (token: string) => `⁦${token}⁩`;

const en: PolicyContent = {
  title: "Privacy Policy",
  lastUpdated: "25 July 2026",
  intro: [
    "RUNI Market is a student-run marketplace for Reichman University students in Herzliya. It is a side project, not an official Reichman University initiative.",
    "This policy explains what personal data we collect, why we collect it, who can see it, and what you can do about it. We deliberately keep data collection to the minimum the marketplace needs to work: there is no advertising, no tracking, no analytics, and no payment processing anywhere in this service.",
  ],
  sections: [
    {
      heading: "Who is responsible",
      body: [
        `RUNI Market operates this website and decides how the data described here is handled. For any privacy question or request, contact ${PRIVACY_CONTACT_EMAIL}.`,
      ],
    },
    {
      heading: "What we collect",
      body: ["We collect only the following, all of it provided by you or generated by your use of the site:"],
      bullets: [
        "Account details: your Reichman email address (registration is restricted to @post.runi.ac.il), the name you enter at signup, and the date your email was confirmed. Your password is never visible to us; it is hashed and stored by our authentication provider.",
        "Listings you post: title, description, price, category, condition, handover location (on or off campus), and any photos you upload.",
        "Messages: the content and timestamps of chat messages you exchange with other students about a listing, plus whether a message has been read.",
        "Watchlist: which listings you have saved.",
        "Reports: if you report a listing, we store the report, the listing it concerns and your user ID, so admins can act on it.",
        "Technical data stored in your browser: a login session token and your language preference (English or Hebrew). Our hosting and email providers also keep standard server logs, which may include IP addresses, for security and reliability.",
      ],
    },
    {
      heading: "What we do not collect",
      body: [
        "We do not use analytics, advertising networks, social media pixels or any third-party tracking. We set no tracking or advertising cookies. We never handle payment or bank details: all payments happen directly between students in person, outside this service. We do not sell or rent your personal data to anyone, and we do not use it to train machine learning models.",
      ],
    },
    {
      heading: "Why we use your data and on what legal basis",
      body: ["Under the EU GDPR (where it applies to you) our legal bases are:"],
      bullets: [
        "Performance of a contract: creating and maintaining your account, publishing your listings, delivering your messages, and keeping your watchlist.",
        "Legitimate interests: keeping the marketplace safe and usable, which includes reviewing reported listings, enforcing the limits on listings and photos, and preventing abuse and fraud.",
        "Legal obligation: retaining or disclosing data where the law requires it.",
      ],
    },
    {
      heading: "Who can see your data",
      body: [
        "Different data has different visibility, and it is worth understanding the difference before you post:",
      ],
      bullets: [
        "Public to anyone, including visitors without an account: your active listings, their photos, price, category, condition, handover location and how many people have saved them. Do not put anything in a listing title, description or photo that you would not want publicly visible.",
        "Revealed when you start a chat: listing pages do not show the seller's name. Your name becomes visible to the other person once a conversation is opened, so buyer and seller can recognise each other when they meet on campus.",
        "Private to the participants: the content of your chat messages. Site administrators can access message data where it is technically necessary to run or troubleshoot the service, and to investigate reported abuse.",
        "Administrators only: reports you submit, and the moderation decisions taken on them.",
      ],
    },
    {
      heading: "Service providers",
      body: [
        "We rely on a small number of providers who process data on our behalf. They are bound to use it only to deliver their service to us:",
      ],
      bullets: [
        "Supabase: database, authentication, file storage and realtime messaging. This is where your account, listings, photos and messages are stored.",
        "Resend: sending transactional email only, meaning signup confirmations and notifications that you have received a new message.",
        "GitHub Pages: hosting the website files that your browser loads.",
        "These providers may store or process data on servers outside Israel and outside the European Economic Area. Where the GDPR applies, such transfers rely on the safeguards offered by those providers, such as standard contractual clauses.",
      ],
    },
    {
      heading: "How long we keep data",
      body: [
        "Your account data is kept for as long as your account exists. Listings and their photos are kept until you delete them or delete your account. Messages remain available to both participants so the conversation history stays intact for the other student. Deleting your account removes your profile, listings, photos, watchlist and associated records from our database; backups held by our providers may retain copies for a short period before they expire. Server logs held by our providers are kept according to their own retention schedules.",
      ],
    },
    {
      heading: "Your rights and how to exercise them",
      body: [
        "You can access, correct, export or delete your personal data. Several of these you can do yourself, immediately and without asking us:",
      ],
      bullets: [
        "Correct your name: edit it on your profile page.",
        "Remove content: delete individual listings and photos from My Listings, or clear items from your watchlist.",
        "Delete your account: use the Delete account option on your profile page. This permanently deletes your account and cascades to your listings, photos and watchlist.",
        `Anything else, including a copy of your data or a restriction of or objection to processing: email ${PRIVACY_CONTACT_EMAIL} and we will respond within the timeframe required by applicable law.`,
        "You also have the right to complain to a supervisory authority: in Israel the Privacy Protection Authority, or in the EEA your local data protection authority.",
      ],
    },
    {
      heading: "Security",
      body: [
        "Access to data is enforced at the database level with row-level security policies, not only in the app, so one user cannot read another user's private data. All traffic is served over HTTPS, passwords are hashed by our authentication provider, and registration is restricted to verified Reichman University email addresses. No system is perfectly secure, so please use a strong, unique password and be careful about what personal information you put into listings and messages.",
      ],
    },
    {
      heading: "Meeting in person",
      body: [
        "Trades are arranged between students and take place in person, typically on campus. RUNI Market is not a party to those trades and does not vet users beyond checking that they hold a Reichman University email address. Please use common sense: meet in a public place on campus, and share only the contact details you are comfortable sharing.",
      ],
    },
    {
      heading: "Children",
      body: [
        "This service is intended for Reichman University students and is not directed at children. Registration requires a university email address.",
      ],
    },
    {
      heading: "Changes to this policy",
      body: [
        "If we change how we handle personal data, we will update this page and the date shown at the top. Significant changes will be communicated in the app or by email.",
      ],
    },
    {
      heading: "Contact",
      body: [
        `For any question about this policy or about your data, contact ${PRIVACY_CONTACT_EMAIL}.`,
      ],
    },
  ],
};

const he: PolicyContent = {
  title: "מדיניות פרטיות",
  lastUpdated: "25 ביולי 2026",
  intro: [
    "רייכמן מרקט הוא זירת מסחר לסטודנטים של אוניברסיטת רייכמן בהרצליה, המופעלת על ידי סטודנטים. מדובר בפרויקט צד ולא ביוזמה רשמית של אוניברסיטת רייכמן.",
    "מדיניות זו מסבירה אילו נתונים אישיים אנחנו אוספים, לשם מה, מי יכול לראות אותם ומה באפשרותכם לעשות בנוגע אליהם. אנחנו אוספים במכוון רק את המינימום הדרוש לתפעול הזירה: אין פרסום, אין מעקב, אין כלי ניתוח ואין עיבוד תשלומים בשירות הזה.",
  ],
  sections: [
    {
      heading: "מי אחראי",
      body: [
        `רייכמן מרקט מפעיל את האתר הזה ומחליט כיצד מטופלים הנתונים המתוארים כאן. לכל שאלה או בקשה בנושא פרטיות אפשר לפנות לכתובת ${ltr(PRIVACY_CONTACT_EMAIL)}.`,
      ],
    },
    {
      heading: "אילו נתונים אנחנו אוספים",
      body: ["אנחנו אוספים רק את הפרטים הבאים, כולם נמסרים על ידיכם או נוצרים כתוצאה מהשימוש שלכם באתר:"],
      bullets: [
        `פרטי חשבון: כתובת הדוא"ל שלכם באוניברסיטת רייכמן (ההרשמה מוגבלת לכתובות ${ltr("@post.runi.ac.il")}), השם שהזנתם בהרשמה ומועד אימות הדוא"ל. הסיסמה שלכם לעולם אינה גלויה לנו; היא נשמרת בגיבוב אצל ספק האימות שלנו.`,
        "מודעות שאתם מפרסמים: כותרת, תיאור, מחיר, קטגוריה, מצב הפריט, מקום המסירה (בקמפוס או מחוצה לו) וכל תמונה שאתם מעלים.",
        "הודעות: התוכן והחותמות של הודעות הצ'אט שאתם מחליפים עם סטודנטים אחרים בנוגע למודעה, וכן האם הודעה נקראה.",
        "רשימת מעקב: אילו מודעות שמרתם.",
        "דיווחים: אם דיווחתם על מודעה, אנחנו שומרים את הדיווח, המודעה שאליה הוא מתייחס ומזהה המשתמש שלכם, כדי שמנהלי המערכת יוכלו לטפל בו.",
        "נתונים טכניים הנשמרים בדפדפן שלכם: אסימון התחברות והעדפת השפה (אנגלית או עברית). ספקי האחסון והדוא\"ל שלנו שומרים גם יומני שרת רגילים, שעשויים לכלול כתובות IP, לצורכי אבטחה ויציבות.",
      ],
    },
    {
      heading: "מה איננו אוספים",
      body: [
        "איננו משתמשים בכלי ניתוח, ברשתות פרסום, בפיקסלים של רשתות חברתיות או בכל מעקב של צד שלישי. איננו מציבים עוגיות מעקב או פרסום. איננו מטפלים בפרטי תשלום או בפרטי בנק: כל התשלומים מתבצעים ישירות בין הסטודנטים באופן אישי, מחוץ לשירות הזה. איננו מוכרים או משכירים את הנתונים האישיים שלכם לאיש, ואיננו משתמשים בהם לאימון מודלים של למידת מכונה.",
      ],
    },
    {
      heading: "לשם מה אנחנו משתמשים בנתונים ומהו הבסיס החוקי",
      body: ["על פי ה-GDPR האירופי, במקרים שבהם הוא חל עליכם, הבסיס החוקי שלנו הוא:"],
      bullets: [
        "ביצוע חוזה: יצירת החשבון שלכם ותחזוקתו, פרסום המודעות שלכם, העברת ההודעות שלכם וניהול רשימת המעקב.",
        "אינטרסים לגיטימיים: שמירה על זירה בטוחה ושמישה, לרבות בדיקת מודעות שדווחו, אכיפת המגבלות על מספר המודעות והתמונות ומניעת ניצול לרעה והונאה.",
        "חובה חוקית: שמירת נתונים או מסירתם כאשר החוק מחייב זאת.",
      ],
    },
    {
      heading: "מי יכול לראות את הנתונים שלכם",
      body: ["לנתונים שונים יש רמות חשיפה שונות, וכדאי להבין את ההבדל לפני שמפרסמים:"],
      bullets: [
        "גלוי לכולם, כולל למבקרים ללא חשבון: המודעות הפעילות שלכם, התמונות שלהן, המחיר, הקטגוריה, מצב הפריט, מקום המסירה ומספר האנשים ששמרו אותן. אל תכללו בכותרת, בתיאור או בתמונה של מודעה דבר שלא הייתם רוצים שיהיה גלוי לציבור.",
        "נחשף כשמתחילים צ'אט: בעמודי המודעות לא מוצג שם המוכר. השם שלכם נחשף לצד השני ברגע שנפתחת שיחה, כדי שהקונה והמוכר יוכלו לזהות זה את זה בפגישה בקמפוס.",
        "פרטי למשתתפים: תוכן הודעות הצ'אט שלכם. מנהלי האתר יכולים לגשת לנתוני הודעות כאשר הדבר נחוץ מבחינה טכנית לתפעול השירות או לאיתור תקלות, וכן לצורך בדיקת דיווחים על ניצול לרעה.",
        "למנהלי המערכת בלבד: דיווחים שהגשתם וההחלטות שהתקבלו בעקבותיהם.",
      ],
    },
    {
      heading: "ספקי שירות",
      body: [
        "אנחנו נעזרים במספר קטן של ספקים המעבדים נתונים בשמנו. הם מחויבים להשתמש בהם רק לצורך אספקת השירות שלהם לנו:",
      ],
      bullets: [
        "Supabase: מסד נתונים, אימות משתמשים, אחסון קבצים והודעות בזמן אמת. שם נשמרים החשבון, המודעות, התמונות וההודעות שלכם.",
        "Resend: שליחת דוא\"ל תפעולי בלבד, כלומר אישורי הרשמה והתראות על קבלת הודעה חדשה.",
        "GitHub Pages: אחסון קובצי האתר שהדפדפן שלכם טוען.",
        "ספקים אלה עשויים לאחסן או לעבד נתונים בשרתים מחוץ לישראל ומחוץ לאזור הכלכלי האירופי. במקרים שבהם ה-GDPR חל, העברות אלה נסמכות על אמצעי ההגנה שמציעים אותם ספקים, כגון תניות חוזיות סטנדרטיות.",
      ],
    },
    {
      heading: "כמה זמן אנחנו שומרים נתונים",
      body: [
        "נתוני החשבון שלכם נשמרים כל עוד החשבון קיים. מודעות והתמונות שלהן נשמרות עד שתמחקו אותן או תמחקו את החשבון. הודעות נשארות זמינות לשני המשתתפים כדי שהיסטוריית השיחה תישמר עבור הסטודנט שמולכם. מחיקת החשבון מסירה ממסד הנתונים שלנו את הפרופיל, המודעות, התמונות, רשימת המעקב והרשומות הנלוות; גיבויים המוחזקים אצל הספקים שלנו עשויים להכיל עותקים לתקופה קצרה עד לפקיעתם. יומני שרת המוחזקים אצל הספקים נשמרים על פי מדיניות השמירה שלהם.",
      ],
    },
    {
      heading: "הזכויות שלכם וכיצד לממש אותן",
      body: [
        "אתם רשאים לגשת לנתונים האישיים שלכם, לתקן אותם, לייצא אותם או למחוק אותם. חלק מהפעולות אפשר לבצע לבד, מיד וללא פנייה אלינו:",
      ],
      bullets: [
        "תיקון השם: אפשר לערוך אותו בעמוד הפרופיל.",
        "הסרת תוכן: אפשר למחוק מודעות ותמונות בודדות דרך \"המודעות שלי\", או להסיר פריטים מרשימת המעקב.",
        "מחיקת החשבון: דרך האפשרות \"מחיקת חשבון\" בעמוד הפרופיל. פעולה זו מוחקת לצמיתות את החשבון ואיתו את המודעות, התמונות ורשימת המעקב.",
        `לכל בקשה אחרת, לרבות קבלת עותק של הנתונים שלכם או הגבלת העיבוד או התנגדות לו: שלחו דוא"ל לכתובת ${ltr(PRIVACY_CONTACT_EMAIL)} ואנחנו נשיב בתוך פרק הזמן הקבוע בדין החל.`,
        "כמו כן עומדת לכם הזכות להגיש תלונה לרשות פיקוח: בישראל הרשות להגנת הפרטיות, ובאזור הכלכלי האירופי רשות הגנת המידע המקומית שלכם.",
      ],
    },
    {
      heading: "אבטחה",
      body: [
        "הגישה לנתונים נאכפת ברמת מסד הנתונים באמצעות מדיניות אבטחה ברמת השורה, ולא רק באפליקציה, כך שמשתמש אחד אינו יכול לקרוא נתונים פרטיים של משתמש אחר. כל התעבורה מוגשת באמצעות HTTPS, הסיסמאות נשמרות בגיבוב אצל ספק האימות שלנו, וההרשמה מוגבלת לכתובות דוא\"ל מאומתות של אוניברסיטת רייכמן. אף מערכת אינה מאובטחת באופן מושלם, ולכן השתמשו בסיסמה חזקה וייחודית והקפידו על המידע האישי שאתם מוסרים במודעות ובהודעות.",
      ],
    },
    {
      heading: "פגישות פנים אל פנים",
      body: [
        "העסקאות נקבעות בין הסטודנטים ומתבצעות באופן אישי, בדרך כלל בקמפוס. רייכמן מרקט אינו צד לעסקאות אלה ואינו בודק את המשתמשים מעבר לאימות שברשותם כתובת דוא\"ל של אוניברסיטת רייכמן. נהגו בשיקול דעת: היפגשו במקום ציבורי בקמפוס ומסרו רק את פרטי הקשר שנוח לכם למסור.",
      ],
    },
    {
      heading: "קטינים",
      body: [
        "השירות מיועד לסטודנטים של אוניברסיטת רייכמן ואינו מכוון לילדים. ההרשמה מחייבת כתובת דוא\"ל אוניברסיטאית.",
      ],
    },
    {
      heading: "שינויים במדיניות זו",
      body: [
        "אם נשנה את אופן הטיפול בנתונים אישיים, נעדכן עמוד זה ואת התאריך המופיע בראשו. על שינויים משמעותיים נודיע באפליקציה או בדוא\"ל.",
      ],
    },
    {
      heading: "יצירת קשר",
      body: [
        `לכל שאלה בנוגע למדיניות זו או לנתונים שלכם, פנו לכתובת ${ltr(PRIVACY_CONTACT_EMAIL)}.`,
      ],
    },
  ],
};

export const privacyPolicy: Record<Language, PolicyContent> = { en, he };
