-- ============================================================
-- CACHED LISTING TRANSLATIONS
-- ============================================================
-- Translations are generated by the translate-listing Edge Function and
-- cached here so product cards do not repeatedly call the model.

CREATE TABLE IF NOT EXISTS public.listing_translations (
  listing_id UUID NOT NULL REFERENCES public.listings(id) ON DELETE CASCADE,
  language TEXT NOT NULL CHECK (language IN ('en', 'he')),
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (listing_id, language)
);

ALTER TABLE public.listing_translations ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Anyone can view listing translations" ON public.listing_translations;
CREATE POLICY "Anyone can view listing translations"
  ON public.listing_translations FOR SELECT
  USING (true);

CREATE INDEX IF NOT EXISTS listing_translations_language_idx
  ON public.listing_translations(language);

CREATE OR REPLACE FUNCTION public.touch_listing_translations_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SET search_path = public;

DROP TRIGGER IF EXISTS touch_listing_translations_updated_at ON public.listing_translations;
CREATE TRIGGER touch_listing_translations_updated_at
  BEFORE UPDATE ON public.listing_translations
  FOR EACH ROW EXECUTE FUNCTION public.touch_listing_translations_updated_at();

CREATE OR REPLACE FUNCTION public.clear_listing_translations()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.title IS DISTINCT FROM OLD.title OR NEW.description IS DISTINCT FROM OLD.description THEN
    DELETE FROM public.listing_translations WHERE listing_id = NEW.id;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

REVOKE EXECUTE ON FUNCTION public.clear_listing_translations() FROM PUBLIC, anon, authenticated;

DROP TRIGGER IF EXISTS clear_listing_translations_on_listing_update ON public.listings;
CREATE TRIGGER clear_listing_translations_on_listing_update
  AFTER UPDATE OF title, description ON public.listings
  FOR EACH ROW EXECUTE FUNCTION public.clear_listing_translations();
